config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "pages#home"
  get "/about", to: "pages#about"
  # VERB "/url_path", to: "controller#action"
  get "/contact", to: "pages#contact" # , as: "contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # actions
  # (methods that are defined in the controller)
  def home
  end

  def about
  end

  def contact
    @members = ["claire", "sarah", "kat", "soojin"]
    if params[:member] # if you even did a search
      @members = @members.select do |member|
        # if this is true, then the item stays in the final result
        # if it's false, the item gets removed
        member.start_with?(params[:member].downcase)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Our Spoon 🥄</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1>Welcome to Our Spoon 🥄</h1>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
    <%= yield %>
    <p>Made during lecture at Le Wagon</p>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Our Spoon 🥄</h1>

<p>We are a restaurant review site, yay!</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>

<p>We would be happy to hear from you</p>

<form action="/contact">
  <label for="member">Who do you want to search for?</label>
  <input
    id="member"
    name="member"
    value="<%= params[:member] %>"
    type="text">

  <input value="Search" type="submit">
</form>

<p>You searched for <%= params[:member] %></p>

<ul>
  <% @members.each do |member| %>
    <li><%= member.capitalize %></li>
  <% end %>
</ul>

<a href="https://www.google.com">Go to Google</a>
<%= link_to "Go to Google", "https://www.google.com" %>

<%= link_to "Go to the homepage", root_path %>

app/views/pages/home.html.erb
<h1>The sum is <%= 4 + 5 %></h1>

<p>The time is <%= Time.now %></p>

<% magic_number = 6 %>

<p>The magic number is <%= magic_number %>.</p>